import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

export interface PdfExportMeta {
  appName: string;
  fileName: string;
  rowCount: number;
  colCount: number;
  chartCount: number;
  tableCount: number;
  insightCount: number;
  logoUrl?: string;
  /** Accent stripe color for the cover page and page headers. Defaults to the app's indigo. */
  accentColor?: [number, number, number];
}

const A4_WIDTH_MM = 210;
const A4_HEIGHT_MM = 297;
const MARGIN_MM = 12;

async function loadImageAsDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function drawCoverPage(pdf: jsPDF, meta: PdfExportMeta, logoDataUrl: string | null) {
  const pageW = A4_WIDTH_MM;
  const pageH = A4_HEIGHT_MM;
  const [ar, ag, ab] = meta.accentColor ?? [99, 102, 241];

  // Background block
  pdf.setFillColor(15, 23, 42);
  pdf.rect(0, 0, pageW, pageH, 'F');

  // Accent stripe
  pdf.setFillColor(ar, ag, ab);
  pdf.rect(0, 0, pageW, 6, 'F');

  if (logoDataUrl) {
    try {
      pdf.addImage(logoDataUrl, 'PNG', pageW / 2 - 18, 60, 36, 36);
    } catch {
      // ignore
    }
  }

  pdf.setTextColor(255, 255, 255);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(28);
  pdf.text(meta.appName, pageW / 2, 115, { align: 'center' });

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(16);
  pdf.setTextColor(203, 213, 225);
  pdf.text('Dashboard Report', pageW / 2, 128, { align: 'center' });

  // Card with metadata
  pdf.setFillColor(30, 41, 59);
  pdf.roundedRect(30, 150, pageW - 60, 90, 4, 4, 'F');

  pdf.setFontSize(11);
  pdf.setTextColor(148, 163, 184);
  const labelX = 40;
  const valueX = pageW - 40;

  const rows: Array<[string, string]> = [
    ['Source file', meta.fileName || '—'],
    ['Generated', new Date().toLocaleString()],
    ['Rows × Columns', `${meta.rowCount.toLocaleString()} × ${meta.colCount}`],
    ['Charts', String(meta.chartCount)],
    ['Tables', String(meta.tableCount)],
    ['Insights', String(meta.insightCount)],
  ];

  rows.forEach(([label, value], i) => {
    const y = 162 + i * 12;
    pdf.setTextColor(148, 163, 184);
    pdf.text(label, labelX, y);
    pdf.setTextColor(255, 255, 255);
    pdf.text(value, valueX, y, { align: 'right' });
  });

  pdf.setFontSize(9);
  pdf.setTextColor(100, 116, 139);
  pdf.text('Generated by ExcelInsight', pageW / 2, pageH - 15, { align: 'center' });
}

export async function exportDashboardToPDF(
  container: HTMLElement,
  meta: PdfExportMeta,
): Promise<void> {
  const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  const logoDataUrl = meta.logoUrl ? await loadImageAsDataUrl(meta.logoUrl) : null;
  drawCoverPage(pdf, meta, logoDataUrl);

  // Find each card (direct children of grid)
  const cards = Array.from(container.querySelectorAll<HTMLElement>('[data-pdf-card]'));
  if (!cards.length) {
    pdf.save(`${meta.appName}-Dashboard-${Date.now()}.pdf`);
    return;
  }

  // Hide controls during capture
  const hiddenEls: Array<{ el: HTMLElement; prev: string }> = [];
  container.querySelectorAll<HTMLElement>('[data-pdf-hide]').forEach((el) => {
    hiddenEls.push({ el, prev: el.style.visibility });
    el.style.visibility = 'hidden';
  });

  const bgColor = getComputedStyle(document.body).backgroundColor || '#ffffff';

  try {
    const usableW = A4_WIDTH_MM - MARGIN_MM * 2;
    const usableH = A4_HEIGHT_MM - MARGIN_MM * 2 - 10; // leave space for footer

    let cursorY = MARGIN_MM;
    let pageNum = 1;
    pdf.addPage();
    pageNum++;

    // header on each content page
    const [ar, ag, ab] = meta.accentColor ?? [99, 102, 241];
    const drawPageHeader = () => {
      pdf.setFillColor(ar, ag, ab);
      pdf.rect(0, 0, A4_WIDTH_MM, 4, 'F');
      pdf.setFontSize(9);
      pdf.setTextColor(100, 116, 139);
      pdf.text(meta.appName + ' — Dashboard Report', MARGIN_MM, 9);
      pdf.text(meta.fileName, A4_WIDTH_MM - MARGIN_MM, 9, { align: 'right' });
      pdf.setDrawColor(226, 232, 240);
      pdf.line(MARGIN_MM, 11, A4_WIDTH_MM - MARGIN_MM, 11);
    };

    drawPageHeader();
    cursorY = MARGIN_MM + 6;

    for (const card of cards) {
      const canvas = await html2canvas(card, {
        backgroundColor: bgColor,
        scale: 2,
        useCORS: true,
        logging: false,
      });
      const imgData = canvas.toDataURL('image/png');
      const imgW = usableW;
      const imgH = (canvas.height * imgW) / canvas.width;

      // If exceeds page, scale down to fit page or start a new page
      if (imgH > usableH) {
        // Scale to fit a full page
        const scaledH = usableH;
        const scaledW = (canvas.width * scaledH) / canvas.height;
        if (cursorY > MARGIN_MM + 6) {
          pdf.addPage();
          pageNum++;
          drawPageHeader();
          cursorY = MARGIN_MM + 6;
        }
        const offsetX = MARGIN_MM + (usableW - scaledW) / 2;
        pdf.addImage(imgData, 'PNG', offsetX, cursorY, scaledW, scaledH);
        cursorY += scaledH + 4;
        continue;
      }

      if (cursorY + imgH > A4_HEIGHT_MM - MARGIN_MM) {
        pdf.addPage();
        pageNum++;
        drawPageHeader();
        cursorY = MARGIN_MM + 6;
      }

      pdf.addImage(imgData, 'PNG', MARGIN_MM, cursorY, imgW, imgH);
      cursorY += imgH + 4;
    }

    // Footer page numbers
    const total = pdf.getNumberOfPages();
    for (let i = 2; i <= total; i++) {
      pdf.setPage(i);
      pdf.setFontSize(9);
      pdf.setTextColor(100, 116, 139);
      pdf.text(`Page ${i - 1} of ${total - 1}`, A4_WIDTH_MM / 2, A4_HEIGHT_MM - 6, { align: 'center' });
    }
  } finally {
    hiddenEls.forEach(({ el, prev }) => { el.style.visibility = prev; });
  }

  const safeName = (meta.fileName || 'data').replace(/\.[^.]+$/, '').replace(/[^\w-]+/g, '_').slice(0, 40);
  const dateStr = new Date().toISOString().slice(0, 10);
  pdf.save(`${meta.appName}-Dashboard-${safeName}-${dateStr}.pdf`);
}
